<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="chihongyuan0001" name="gxyjTest" tests="3" failures="2" timestamp="19 Jun 2018 02:41:28 GMT" time="38.223" errors="0">
  <testcase name="index" time="14.208" classname="com.gxyj.web.Web01">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at com.gxyj.util.CheckPoint.result(CheckPoint.java:54)
	at com.gxyj.web.Web01.index(Web01.java:18)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- index -->
  <testcase name="index" time="11.125" classname="com.gxyj.web.Web01">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
	at com.gxyj.util.CheckPoint.result(CheckPoint.java:54)
	at com.gxyj.web.Web01.index(Web01.java:18)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- index -->
  <testcase name="register" time="5.204" classname="com.gxyj.web.Web02"/>
</testsuite> <!-- gxyjTest -->
